spring:
  application:
    name: spring-cloud-admin-server
  boot:
    admin:
      context-path: /admin

server:
  port: 8888

#注册中心地址 可集群
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  security:
    enabled: false
