spring:
  application:
    name: myCloudRegister
  profiles:
    active: dev

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
  server:
    disable-delta: true

endpoints:
  shutdown:
    enabled: true

