spring:
  application:
    name: myCloudConsumer
  profiles:
    active: dev

server:
  port: 9100

#注册中心地址 可集群
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


#启动熔断机制
feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false

##不起用懒加载
ribbon:
  eager-load:
    enabled: true
    clients: myCloudProvider
