spring:
  application:
    name: myCloudHystrix
  profiles:
    active: dev

server:
  port: 9200

#注册中心地址 可集群
eureka:
  client:
    service-url:
      defaultZone: http://deveureka:8080/eureka/

#熔断监控
turbine:
  app-config: myCloudConsumer
  aggeregator:
    clusterConfig: default
  clusterNameExpression: new String("default")