spring:
  application:
    name: myCloudProvider
  profiles:
    active: dev

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  security:
    enabled: false



