spring:
  application:
    name: myCloudProvider
  profiles:
    active: dev
    ##可以包含的配置文件
    include: xxx,yyy
  #服务追踪
  zipkin:
      base-url: http://localhost:9500

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://Marco.local:8080/eureka/

#安全验证开关
management:
  security:
    enabled: false
