spring:
  application:
    name: myCloudProvider
  profiles:
    active: dev
    ##可以包含的配置文件
    include: xxx,yyy

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  security:
    enabled: false
